### ISSUE TITLE
Mannually building HLS

### ISSUE THREAD

**Issue by SeungheonOh** [Liqwid-Labs/liqwid-nix#32]
We are building HLS, as well as other utility like formolu, from the source. Why can't we use cache provided by haskell.nix?

**Comment by SeungheonOh** [comment]
I think we can use `haskell-language-server` from `haskell.nix` it seems to work fine, though I never tested using my editor as it was too much hassle to set LSP up all again

**Comment by emiflake** [comment]
I think we can close this now, let's see how it ends up going.
