### ISSUE TITLE
CTL server obsolete

### ISSUE THREAD

**Issue by aciceri** [Liqwid-Labs/liqwid-nix#59]
Does `liqwid-nix` target CTL v5, right? I believe that `ctl-server` is no more used now, I don't think that the overlay even exists anymore. https://github.com/Liqwid-Labs/liqwid-nix/blob/c763f911371def8c96a3191e5a1e549d4b501ee0/nix/offchain.nix#L393

**Comment by emiflake** [comment]
Fixed in #67.
