### ISSUE TITLE
Allowing tools from other `nixpkgs`

### ISSUE THREAD

**Issue by SeungheonOh** [Liqwid-Labs/liqwid-nix#6]
Currently, `addCommandLineTools` and other utilities receive packages like following: 
```nix
(pkg: pkg': [ pkg.your pkg'.packages pkg.here ] )
```
While this design in clean, this prevent adding packages from input other than `inputs.nixpkgs` or `inputs.nixpkgs-latest`. Should we make another function to do this? I believe, for some tooling, we need specific versions. Specifically, @peter-mlabs reported `apply-refact` broke in new flake using `liqwid-nix`, and I suspect it is due to mismatch in version.

**Comment by emiflake** [comment]
I'd expect we might want to just be given `self`?

**Comment by SeungheonOh** [comment]
How would one get packages from `self`? The packages need to have `system` set, which I don't think is possible with `self`

**Comment by peter-mlabs** [comment]
Moved to notion:
https://www.notion.so/liqwid/Allowing-tools-from-other-nixpkgs-bca0d1eb965443a0a3d3f1d7a2ce7ea0
