### ISSUE TITLE
Autogenerated reference docs starting from modules options

### ISSUE THREAD

**Issue by aciceri** [Liqwid-Labs/liqwid-nix#60]
I really like this project, it's exactly how `mlabs-tooling.nix` should have been in my opinion. Any plan to make autogenerated docs starting from modules options? Like [haskell.nix docs here](https://input-output-hk.github.io/haskell.nix/reference/modules.html) or [flake.parts docs here](https://flake.parts/options/flake-parts.html). Then it would be possible hosting docs using the [Hercules CI's Githug Pages effect](https://docs.hercules-ci.com/hercules-ci-effects/guide/deploy-to-github-pages) in a few lines.

**Comment by emiflake** [comment]
This is something I took a brief look at in the past, but didn't commit to fully. This is absolutely something we want. If you (or anyone else) would like to take a shot at implementing this, feel free to! Otherwise, I'll try it when time allows 🙂

**Comment by emiflake** [comment]
For future reference: `haskell.nix` uses `pkgs.nixosOptionsDoc`, see [the documentation](https://github.com/NixOS/nixpkgs/blob/db21819e91aee7d2bc2edb5845bdad65cddb5cee/nixos/lib/make-options-doc/default.nix), and their [update script](https://github.com/input-output-hk/haskell.nix/blob/master/scripts/update-docs.nix).

**Comment by aciceri** [comment]
I would be happy to implement it, do you think that Liqwid could provide the budget for it?

**Comment by emiflake** [comment]
> I would be happy to implement it, do you think that Liqwid could provide the budget for it?

Hah, looks like you're slightly too late. I've already started working on this. I don't think we can provide budget for it, but it won't take too long until I finish implementation for it.

**Comment by aciceri** [comment]
Great! No problem, I wouldn't have had time until at least next week however. Thanks!
